# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33e1c415949cfd4d2ad8cda615ae23bd41a3aa3fd2a561ff38345351a21a1961bf249722c2a94fd4a2421f0e468bbdc3ab941fc61d141333252b796a98819b3f

test:
  secret_key_base: 083fd4d19f47de951ea80ada573a99ac2be66c49c4d09b739f4000aa91d1df17d9205d402bc3a9522ebfd1e4f76f2c910e300392fe8ac0473b78141ac0c59fe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
